### ISSUE TITLE
[BUG] a wierd behavior of y_label_area_size() with custom Ranged

### ISSUE THREAD

**Issue by sephiron99** [38/plotters#266] opened 2021-06-20 08:15 UTC
I'm using Version 0.3.1, and my code looks like below.
```rust
struct PerHour;

const SEVEN_HRS: u32 = 60 * 7;

impl Ranged for PerHour {
    type ValueType = u32;
    type FormatOption = DefaultFormatting;

    fn map(&self, &v: &u32, pixel_range: (i32, i32)) -> i32 {
       let size = pixel_range.1 - pixel_range.0;
       let v = v.min(SEVEN_HRS).max(0);
        ((v as f64 / SEVEN_HRS as f64) * size as f64) as i32
    }

    fn key_points<Hint:KeyPointHint>(&self, hint: Hint) -> Vec<u32> {
        if hint.max_num_points() < 3 {
            vec![]
        } else {
            vec![0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360, 390]
        }
    }

    fn range(&self) -> Range<u32> {
        std::ops::Range {
            start: 0,
            end: SEVEN_HRS+1,
        }
    }
}

fn get_svg() {
      let root = SVGBackend::with_string(&mut buf, (1280, 800)).into_drawing_area();
        root.fill(&WHITE)?;

        let mut chart = ChartBuilder::on(&root)
            .x_label_area_size(30)
//           Wierd Behavior
//            .y_label_area_size(100)
            .build_cartesian_2d(PerHour, ts.get_lowest()..ts.get_highest())?;

        chart
            .configure_mesh()
            .disable_y_mesh()
            .x_desc("TIME")
            .y_labels(20)
            .x_label_formatter(&|x| (nineoclock + Duration::minutes(*x as i64)).format("%H:%M").to_string())
            .y_label_formatter(&|y| y.to_formatted_string(&Locale::en))
            .draw()?;

        chart
            .draw_series(LineSeries::new(
                PerHour.range().map(get_value_on_minute),
                &BLACK,
            ))?;
    }

    Ok(buf)
}
```
When I don't set `y_label_area_size(100)`, the result looks like this, and there is no problem. 
![image](https://user-images.githubusercontent.com/12970474/122666657-a2921580-d1e9-11eb-830f-3c144e0fd55d.png)

But, When I set `y_label_area_size(100)`,  the result looks like this,
![image](https://user-images.githubusercontent.com/12970474/122666705-ef75ec00-d1e9-11eb-9c30-9aa4b7989ab2.png)

Data located on a area which is set by `y_label_area_size()` are packed into a starting point.

Is this a bug, or my mistake? I can't find a problem of my `impl Ranged for PerHour`.

**Comment by 38** [comment] 2021-06-29 23:16
Hi there, thanks for using Plotters. 

This is caused by your code: the `PerHour::map` is returning wrong coordinate. I just tried on my side

```rust
    fn map(&self, &v: &u32, pixel_range: (i32, i32)) -> i32 {
       let size = pixel_range.1 - pixel_range.0;
       let v = v.min(SEVEN_HRS).max(0);
        ((v as f64 / SEVEN_HRS as f64) * size as f64) as i32 + pixel_range.0  // FIX: don't forget add the base offset
    }

```

Closing the issue and feel free to reopen it if you feel anything is still wrong.

Thanks!

**Closed by 38** 2021-06-29 23:16 UTC
Labels: bug

**Comment by sephiron99** [comment] 2021-06-30 11:34
> 
> 
> Hi there, thanks for using Plotters.
> 
> This is caused by your code: the `PerHour::map` is returning wrong coordinate. I just tried on my side
> 
> ```rust
>     fn map(&self, &v: &u32, pixel_range: (i32, i32)) -> i32 {
>        let size = pixel_range.1 - pixel_range.0;
>        let v = v.min(SEVEN_HRS).max(0);
>         ((v as f64 / SEVEN_HRS as f64) * size as f64) as i32 + pixel_range.0  // FIX: don't forget add the base offset
>     }
> ```
> 
> Closing the issue and feel free to reopen it if you feel anything is still wrong.
> 
> Thanks!

Thank you for your kindness.
Good for your great jobs!
