### ISSUE TITLE
[Feature Request] Better control over mesh grid spacing

### ISSUE THREAD

**Issue by jansegre** [38/plotters#88] opened 2019-11-26 15:13 UTC
### What is the feature ?

Add methods to `plotters::chart::MeshStyle` for configuring the grid spacing.

### (Optional) Why this feature is useful and how people would use the feature?

Basically it'd be useful for making grids for:

- timestamps, controlling the bold grid for days and light grid for hours, or bold grid for hours and light grid for minutes
- log scales, being able to draw irregularly spaced bold and light grids

### (Optional) Additional Information

Maybe a low level API that takes a function or iterator that controls the grid spacing is a good start.

I think [because of this](https://docs.rs/plotters/0.2.11/src/plotters/chart/mesh.rs.html#362) this isn't possible today, but I suspect more places would need changing.

**Comment by 38** [comment] 2019-11-26 17:40
Hi, thanks for the suggestion. 

Yes, this is impossible today, but I think the problem is we are missing the hint in the `key_points` trait method. I believe the only thing we need to do is add an parameter to `Ranged::key_points` to specify if we are asking bold key points or light key points. 

Although I believe this isn't a really big change, it would considering a minor breaking change. Since it may break external define range coord spec.  

So I would like add this in next major release.

Thanks for the suggestion! Cheers!

**Comment by 38** [comment] 2020-05-29 05:01
Closing the issue, due to the key point hint trait code merged to v0.3 branch

**Closed by 38** 2020-05-29 05:01 UTC
Labels: feature request
