### ISSUE TITLE
[BUG] no method named `draw` found

### ISSUE THREAD

**Issue by shinokada** [38/plotters#154] opened 2020-06-13 08:53 UTC
**Describe the bug**

Following the [doc](https://plotters-rs.github.io/book/intro/getting_started.html), when I run cargo run, I get the following error:

![image](https://user-images.githubusercontent.com/147320/84564658-43135580-ad9e-11ea-9997-48d0d3414c4e.png)

In VS code:

![image](https://user-images.githubusercontent.com/147320/84564711-a1403880-ad9e-11ea-8131-e714402d08d7.png)

**To Reproduce**

src/main.rs

```
use plotters::prelude::*;

fn main() {
    let root_drawing_area = BitMapBackend::new("result.png", (1024, 768)).into_drawing_area();

    root_drawing_area.fill(&WHITE);

    let chart = ChartBuilder::on(&root_drawing_area)
        .build_ranged(-3.14..3.14, -1.2..1.2)
        .unwrap();

    chart.draw(LineSeries::new(
            (-314..314).map(|x| x as f64 / 100.0).map(|x| (x, x.sin())),
            &RED,
        ))
        .unwrap();
}
```

**Version Information**

```
[package]
name = "myplotters"
version = "0.1.0"
authors = ["My Name <my.email@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.2.15
```

**Comment by 38** [comment] 2020-06-29 21:14
Hi there, sorry for the delay. It seems you need to used `draw_series` instead of `draw`. 

Closing this issue, feel free to reopen it if the problem is still there.

**Closed by 38** 2020-06-29 21:14 UTC
Labels: bug
