### ISSUE TITLE
[BUG] Silent fail if output directory does not exist

### ISSUE THREAD

**Issue by Volker-Weissmann** [38/plotters#264] opened 2021-06-02 01:57 UTC
**Describe the bug**
If run `mkdir images` and then `cargo run` with example code from [the docs](https://plotters-rs.github.io/book/intro/getting_started.html)
```
use plotters::prelude::*;

fn main() {
    let root_drawing_area = BitMapBackend::new("images/0.1.png", (1024, 768))
        .into_drawing_area();

    root_drawing_area.fill(&WHITE).unwrap();

    let mut chart = ChartBuilder::on(&root_drawing_area)
        .build_cartesian_2d(-3.14..3.14, -1.2..1.2)
        .unwrap();

    chart.draw_series(LineSeries::new(
        (-314..314).map(|x| x as f64 / 100.0).map(|x| (x, x.sin())),
        &RED
    )).unwrap();
}
```
it creates the correct image in `images/0.1.png`. But if I do not run `mkdir images`, plotting fails SILENTLY.

**Version Information**

`plotters = "0.3.1"`

**Comment by 38** [comment] 2021-06-02 16:44
Hi, thanks for trying plotters!

This is a common asked question. 

Actually this is by design, since it's consistent with the standard library: drop should not panic even there's a IO error. See the doc for [std::io::BufWriter](https://doc.rust-lang.org/std/io/struct.BufWriter.html)

> It is critical to call flush before BufWriter<W> is dropped. Though dropping will attempt to flush the contents of the buffer, any errors that happen in the process of dropping will be ignored. Calling flush ensures that the buffer is empty and thus dropping will not even attempt file operations.

 We probably should update the docs so that make people aware this behavior.  

Also, the workaround is calling [present](https://docs.rs/plotters/0.3.1/plotters/drawing/struct.DrawingArea.html#method.present) explicitly and check the return value.

```rust
use plotters::prelude::*;

fn main() {
    let root_drawing_area = BitMapBackend::new("images/0.1.png", (1024, 768))
        .into_drawing_area();

    root_drawing_area.fill(&WHITE).unwrap();

    let mut chart = ChartBuilder::on(&root_drawing_area)
        .build_cartesian_2d(-3.14..3.14, -1.2..1.2)
        .unwrap();

    chart.draw_series(LineSeries::new(
        (-314..314).map(|x| x as f64 / 100.0).map(|x| (x, x.sin())),
        &RED
    )).unwrap();
    root_drawing_area.present().expect("Cannot create result");
}
```

**Comment by 38** [comment] 2021-06-29 23:31
Closing the issue as we made improvement on those examples that is less confusing

**Closed by 38** 2021-06-29 23:31 UTC
Labels: bug

**Comment by Volker-Weissmann** [comment] 2021-09-08 11:46
https://github.com/plotters-rs/guide/pull/7 adds this workaround to the docs
