### ISSUE TITLE
X Labels do not appear for large time ranges

### ISSUE THREAD

**Issue by Geemili** [38/plotters#22] opened 2019-09-05 01:25 UTC
I can't get plotters to render the x_labels for large timespans, no matter how I tweak the parameters. For short timespans it seems fine:
![Screen Shot 2019-09-04 at 20 19 01](https://user-images.githubusercontent.com/2229184/64304437-72fd1500-cf51-11e9-8cab-ee7cd4a900e7.png)

Longer timespans don't show anything:

![Screen Shot 2019-09-04 at 20 20 56](https://user-images.githubusercontent.com/2229184/64304461-85774e80-cf51-11e9-9d56-7c0714f6e517.png)

The code I use for generating the graphs:

```
fn part_graph_view(part: &Part) -> Result<Node<Msg>, Box<dyn std::error::Error>> {
    use plotters::prelude::*;

    let mut buffer = Vec::new();
    {
        let svg = SVGBackend::with_buffer(&mut buffer, (480, 320));
        let root = svg.into_drawing_area();
        root.fill(&WHITE).unwrap();

        let beginning = Utc.from_utc_date(&part.defined);
        let today = Utc::today();
        let (_qty, max_qty, quantities, counts) = part.entries.iter().fold(
            (0_u64, 0_u64, Vec::new(), Vec::new()),
            |(qty, max_qty, mut quantities, mut counts), entry| {
                let qty = match &entry.directive {
                    Directive::Add(d) => {
                        let qty = qty.saturating_add(d.amount);
                        quantities.push((Utc.from_utc_date(&entry.date), qty));
                        qty
                    }
                    Directive::Take(d) => {
                        let qty = qty.saturating_sub(d.amount);
                        quantities.push((Utc.from_utc_date(&entry.date), qty));
                        qty
                    }
                    Directive::Count(d) => {
                        counts.push((Utc.from_utc_date(&entry.date), d.amount));
                        qty
                    }
                    _ => qty,
                };
                (qty, max_qty.max(qty), quantities, counts)
            },
        );

        let mut chart = ChartBuilder::on(&root)
            .caption(part.part_number, ("Arial", 20).into_font())
            .margin(30)
            .x_label_area_size(20)
            .y_label_area_size(20)
            .build_ranged(beginning..today, 0..max_qty)?;

        // TODO: report errors
        chart
            .configure_mesh()
            .label_style(("Arial", 5).into_font())
            .x_label_formatter(&|date| date.format("--%m-%d").to_string())
            .draw()?;

        chart.draw_series(LineSeries::new(quantities, &RED))?;
        chart.draw_series(PointSeries::of_element(
            counts,
            1,
            ShapeStyle::from(&GREEN).filled(),
            &|coord, size, style| {
                EmptyElement::at(coord)
                    + Circle::new((0, 0), size, style)
                    + Text::new(
                        format!("{}, {}", coord.0.naive_utc(), coord.1),
                        (0, -5),
                        ("Arial", 5).into_font(),
                    )
            },
        ))?;
    }

    let svg_text = std::str::from_utf8(&buffer)?;
    Ok(div![El::from_html(svg_text)])
}
```

This code sample isn't really a minimum code sample reproducing the error. I plan on making one soon.

**Comment by 38** [comment] 2019-09-05 18:30
Thanks for reporting this. I am currently looking into it. 

If you have a minimal code reproducing this, that's great. 

Thanks again for your help.

**Comment by 38** [comment] 2019-09-05 20:25
Hi @Geemili ,

I believe I have fixed the issue by adding some missing logic for the `Date` coordinate. 

Please try to use my latest master branch (not any version from crates.io), since I'm not sure if it's working on your side. 

Once we have verified the fix is good, I am going to publish a new version. :-)

Again, thanks for your help!

**Comment by Geemili** [comment] 2019-09-05 22:44
It works now!

![Screen Shot 2019-09-05 at 17 42 23](https://user-images.githubusercontent.com/2229184/64388394-946b0900-d004-11e9-8dfc-fa06baccca36.png)

Now I need to stop the labels from overlapping, but that's a different problem. Thanks for the fix!

**Comment by 38** [comment] 2019-09-05 23:09
No problem. I am closing the issue, feel free to reopen it if you think anything is still wrong. :-)

**Closed by 38** 2019-09-05 23:09 UTC
Labels: bug
