### ISSUE TITLE
[BUG] use of undeclared type or module `LineSeries`

### ISSUE THREAD

**Issue by hasanOryx** [38/plotters#102] opened 2020-01-23 12:58 UTC
I got this error while trying to reproduce your jupyter example:

![image](https://user-images.githubusercontent.com/26045838/72986384-1d8aad00-3df9-11ea-84bc-7598ebf0ed40.png)

**Comment by 38** [comment] 2020-01-23 22:09
Hi there, thanks for reporting this. This is most likely caused by missing features, you probably needs to add "line_series" feature to the top dep session to make it work. 

Thanks for the issue and I am going to clean up the Juypter documentation since it's out-of-dated. 

If you have any question please let me know.

Cheers!

**Comment by 38** [comment] 2020-04-01 18:44
Hi there, Closing the issue now. If you have further problem, please let me know. - Hao

**Closed by 38** 2020-04-01 18:44 UTC
Labels: bug

**Comment by shinokada** [comment] 2020-06-14 06:40
What does "line_series feature to the top dep session to make it work" mean?

Can you give us an example?

Thanks.

**Comment by aseyboldt** [comment] 2020-11-03 11:19
I had the same issue, it should be 
```
:dep plotters = { git = "https://github.com/38/plotters", default_features = false, features = ["evcxr", "line_series"] }
```
@38 Is there a reason this is not included in the readme and examples?
