### ISSUE TITLE
[BUG] Circles display white lines/interruptions when only implementing draw_line of the optional DrawingBackend methods

### ISSUE THREAD

**Issue by arctic-alpaca** [38/plotters#188] opened 2020-09-12 17:50 UTC
**Describe the bug**
When only implementing the required and the optional `draw_line` method of the `DrawingBackend`, the circles aren't quite right in Iced. Here's a screenshot:
![weird_circle](https://user-images.githubusercontent.com/67190338/93001501-b65c6d00-f52f-11ea-8971-79479dd3b8f2.PNG)
This shouldn't be related to the implementation of the Iced backend since the code is pretty straight forward, but I don't want to rule out a problem there.
With only the required methods implemented, this behavior doesn't appear, whith the `draw_circle` method implemented, the behavior disappears again.

**To Reproduce**
Using the code from the [Iced backend](https://github.com/arctic-alpaca/plotters_backend_iced/blob/master/iced_backend/src/backend.rs), comment out all optional methods of the `DrawingBackend` with exception of `draw_line`, then compile the /src/main from the repository. The resulting plot should look like the screenshot.

**Version Information**
Plotters, Iced and Plotters_backends have been cloned from github on 12.09.2020 and are present in the mentioned repository.

**Comment by 38** [comment] 2020-09-12 18:38
I tried the repo, Unfortunately i can't run the code, it fail to start with an error message: GraphicAdapterNotFound

AFAICT, I believe this is caused by the convention difference between Plotters draw_line semantics and iced draw_line semantics. seems iced draw_line semantics produced a shorter line.

**Comment by 38** [comment] 2020-09-12 19:18
I just repo that with svg backend without circle overriding. So, this is caused by in Plotters, drawing a line from (x0, y0) to (x1, y1) means starts from exactly from pos (x0, y0) to exact pos (x1, y1) inclusively. 

This makes both SVG and iced needs to implemented the line drawing method in Plotters' convention. 

But I don't think this is concerning, since it's likely that all backend that can draw a line don't need to use the default rasterizer. And if this is not true, I would argue it's a backend implementation bug, since the backend doesn't follows Plotters' line drawing semantics and this causes circle rasterizer result badly.

**Comment by arctic-alpaca** [comment] 2020-09-12 20:49
Thank you for the explanation!
I'm not sure I can follow it entirely, by not using the default rasterizer, do you mean to override the optional methods or am I missing something here?

> But I don't think this is concerning
I agree, this is just something I noticed while playing around with the Iced backend and I wasn't sure what caused it.

> I tried the repo, Unfortunately i can't run the code, it fail to start with an error message: GraphicAdapterNotFound
Iced supports Vulkan, Metal, DX11, and DX12, is one of them available on your system? Can you run the Iced examples or does it result in the same error?

**Comment by 38** [comment] 2020-09-12 21:54
> do you mean to override the optional methods or am I missing something here?

Plotters actually makes a "minimal backend capability assumption", which means Plotters only requires a set of minimal operations (particularly only one operation is required: draw pixel) to implement all drawing instructions. If a backend missing some capability, it uses its default rasterization algorithm to fill the gap. So if the backend does not override a method,  Plotters should use the builtin rasterizer. This is helpful when we targeting raster graphics backend (e.g. bitmap, console, etc), or any backend with limited graph capabilities. But if the backend has more drawing instructions, it should use the backend's native implementation, especially for those backend that produces vector graph, we generally don't want to raster the shapes in the early stage. 

For example, if SVG backend only implements drawing pixel as a 1px rectangle, you will get a SVG output that is actually a bitmap, it would scale very poorly and we generally don't want that. 

> Iced supports Vulkan, Metal, DX11, and DX12, is one of them available on your system? Can you run the Iced examples or does it result in the same error?

Ah, I see, I don't think my hardware supports that. :(

**Comment by 38** [comment] 2020-09-12 22:05
Also, if you don't mind I am just closing this issue, as it's not a bug - And further discussion are welcomed :)

**Closed by 38** 2020-09-12 22:05 UTC
Labels: bug

**Comment by arctic-alpaca** [comment] 2020-09-14 16:21
Thank you very much for the explanation. This helps me understanding Plotters better.
