### ISSUE TITLE
[BUG] 'static lifetime requirement for AreaSeries

### ISSUE THREAD

**Issue by JakeOShannessy** [38/plotters#62] opened 2019-10-20 21:15 UTC
**Describe the bug**
When using `AreaSeries` the backend is required to be `'static`, e.g. `BitmapBackend<'static>`. This has a number of limitations, the simplest of which is that a filename passed to the backend must have a static lifetime. This is not the case with other series such as `LineSeries`. It seems `AreaSeries` takes a reference to the backend while others do not.

**To Reproduce**
I modified the area chart example from:

```rust
let root = BitMapBackend::new("plotters-doc-data/area-chart.png", (1024, 768)).into_drawing_area();
```

to:

```rust
let filename = "plotters-doc-data/area-chart.png".to_string();
let root = BitMapBackend::new(&filename, (1024, 768)).into_drawing_area();
```

After doing this the example would no longer compile. This reproduces my problem exactly.

**Version Information**
Both `master` and 0.2.9.

**Comment by 38** [comment] 2019-10-20 23:19
Hi @JakeOShannessy ,

Thanks for reporting this. 
This is caused by strict lifetime bounds on the dynamic elements. 
And this is fixed on master, I believe. It would be nice if you can confirm this on your side.

Cheers,
Hao

**Closed** 2019-10-20 23:38 UTC
Labels: bug

**Comment by JakeOShannessy** [comment] 2019-10-21 06:20
All fixed, thanks for the quick response.

**Comment by bart-sensirion-qm** [comment] 2024-07-23 14:18
Hi, it seems this issue has returned. When using dynamic elements (for example by calling .to_dyn() on the elements you're drawing) the `static requirement returns. I noticed because the path parameter in the ::new call to the backend needed to be a reference with `static lifetime.
